<?php return array (
  'table' => 'cron_job',
  'columns' => 
  (object) array(
     'id' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'id',
       'allowNull' => false,
       'type' => 'integer',
       'phpType' => 'integer',
       'dbType' => 'int(11)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 11,
       'precision' => 11,
       'scale' => NULL,
       'isPrimaryKey' => true,
       'autoIncrement' => true,
       'unsigned' => false,
       'comment' => '',
    ),
     'last_id' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'last_id',
       'allowNull' => true,
       'type' => 'integer',
       'phpType' => 'integer',
       'dbType' => 'int(11)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 11,
       'precision' => 11,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'name' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'name',
       'allowNull' => false,
       'type' => 'string',
       'phpType' => 'string',
       'dbType' => 'varchar(255)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 255,
       'precision' => 255,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'schedule' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'schedule',
       'allowNull' => false,
       'type' => 'string',
       'phpType' => 'string',
       'dbType' => 'varchar(255)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 255,
       'precision' => 255,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'command' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'command',
       'allowNull' => false,
       'type' => 'string',
       'phpType' => 'string',
       'dbType' => 'varchar(255)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 255,
       'precision' => 255,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'execution_time' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'execution_time',
       'allowNull' => true,
       'type' => 'integer',
       'phpType' => 'integer',
       'dbType' => 'int(11)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 11,
       'precision' => 11,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'logfile' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'logfile',
       'allowNull' => false,
       'type' => 'string',
       'phpType' => 'string',
       'dbType' => 'varchar(255)',
       'defaultValue' => NULL,
       'enumValues' => NULL,
       'size' => 255,
       'precision' => 255,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
     'active' => 
    (object) array(
       'disableJsonSupport' => false,
       'name' => 'active',
       'allowNull' => false,
       'type' => 'tinyint',
       'phpType' => 'integer',
       'dbType' => 'tinyint(1)',
       'defaultValue' => 1,
       'enumValues' => NULL,
       'size' => 1,
       'precision' => 1,
       'scale' => NULL,
       'isPrimaryKey' => false,
       'autoIncrement' => false,
       'unsigned' => false,
       'comment' => '',
    ),
  ),
  'keys' => 
  array (
  ),
);